[tools]
node = "24.1.0"
npm = "11.4.1"
go = "latest"
rust = "latest"
"cargo:eza" = "latest"
"cargo:ripgrep" = "latest"
"cargo:bat" = "latest"
"go:github.com/jesseduffield/lazygit" = "latest"
"go:github.com/jesseduffield/lazydocker" = "latest"
"cargo:atuin" = "latest"
"cargo:starship" = "latest"
"cargo:bacon" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-watch" = "latest"
"cargo:cargo-workspaces" = "latest"
"cargo:cargo-llvm-cov" = "latest"
"cargo:cargo-deps" = "latest"
fzf = "latest"
"cargo:tree-sitter-cli" = "latest"
"cargo:git-delta" = "latest"
"go:github.com/walles/moor/v2/cmd/moor" = "latest"
"go:google.golang.org/protobuf/cmd/protoc-gen-go" = "latest"
"cargo:fd-find" = "latest"
"go:github.com/cweill/gotests/gotests" = "latest"
"go:gotest.tools/gotestsum" = "latest"

[settings]
idiomatic_version_file_enable_tools = []
